repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Última versión estable conocida (sep 2025)
    hooks:
      - id: end-of-file-fixer         # Asegura una línea en blanco al final de cada archivo
      - id: check-yaml                # Valida sintaxis de archivos YAML
      - id: check-added-large-files   # Avisa si estás añadiendo archivos grandes (por defecto >500kB)
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2  # Última versión estable conocida (sep 2025)
    hooks:
      - id: ruff
        args: [--fix]                 # Formatea y corrige código Python automáticamente
      - id: ruff-format
